root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  pre_cmd = ["&nats-server"]
  cmd = "go build -o ./build/app.bin ./cmd/go_meshcat.go"
  # post_cmd = ["nats-server --signal quit"]
  args_bin = []
  bin = "./build/app.bin"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = ["web", "meshcat", "dist", "main.min.js"]
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false


[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
